# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0estrategy_proto\"\x8d\x02\n\x0fPositionPattern\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x0c\n\x04\x62ook\x18\x03 \x01(\t\x12\x0e\n\x06\x63lient\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x65sk\x18\x05 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x06 \x01(\t\x12\x0c\n\x04\x66low\x18\x07 \x01(\t\x12\r\n\x05group\x18\x08 \x01(\t\x12\x11\n\tportfolio\x18\t \x01(\t\x12\x10\n\x08strategy\x18\n \x01(\t\x12\x0e\n\x06trader\x18\x0b \x01(\t\x12\x12\n\nunderlying\x18\x0c \x01(\t\x12\r\n\x05venue\x18\r \x01(\t\x12\x12\n\ngeneration\x18  \x01(\x05\x12\x10\n\x08\x63urrency\x18( \x01(\t\"\xfa\x01\n\x0eOrderAttribute\x12\x12\n\ninstrument\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x0c\n\x04\x62ook\x18\x03 \x01(\t\x12\x0e\n\x06\x63lient\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x65sk\x18\x05 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x06 \x01(\t\x12\x0c\n\x04\x66low\x18\x07 \x01(\t\x12\r\n\x05group\x18\x08 \x01(\t\x12\x11\n\tportfolio\x18\t \x01(\t\x12\x10\n\x08strategy\x18\n \x01(\t\x12\x0e\n\x06trader\x18\x0b \x01(\t\x12\x12\n\nunderlying\x18\x0c \x01(\t\x12\r\n\x05venue\x18\r \x01(\t\x12\x12\n\ngeneration\x18  \x01(\x05*~\n\x13LiquidityPreference\x12\x1f\n\x1bLiquidityPreference_DEFAULT\x10\x00\x12\"\n\x1eLiquidityPreference_MAKER_ONLY\x10\x01\x12\"\n\x1eLiquidityPreference_TAKER_ONLY\x10\x02*o\n\x12PositionPreference\x12\x1e\n\x1aPositionPreference_DEFAULT\x10\x00\x12\x1b\n\x17PositionPreference_OPEN\x10\x01\x12\x1c\n\x18PositionPreference_CLOSE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIQUIDITYPREFERENCE._serialized_start=557
  _LIQUIDITYPREFERENCE._serialized_end=683
  _POSITIONPREFERENCE._serialized_start=685
  _POSITIONPREFERENCE._serialized_end=796
  _POSITIONPATTERN._serialized_start=33
  _POSITIONPATTERN._serialized_end=302
  _ORDERATTRIBUTE._serialized_start=305
  _ORDERATTRIBUTE._serialized_end=555
# @@protoc_insertion_point(module_scope)
