# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disp_params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64isp_params.proto\x12\x0estrategy_proto\x1a\x0c\x63ommon.proto\"k\n\x11\x44ISPATCHER_PARAMS\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03sym\x18\x02 \x01(\t\x12,\n\x04\x61ttr\x18\x03 \x01(\x0b\x32\x1e.strategy_proto.OrderAttribute\x12\x0e\n\x06to_oms\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'disp_params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPATCHER_PARAMS._serialized_start=51
  _DISPATCHER_PARAMS._serialized_end=158
# @@protoc_insertion_point(module_scope)
