# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_hbt_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_common_pb2 as pb__common__pb2

from pb_common_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pb_hbt_msg.proto\x12\x04omgw\x1a\x0fpb_common.proto\"_\n\x08PB_H_Msg\x12\x0b\n\x03\x64st\x18\x01 \x01(\x0c\x12\x0b\n\x03src\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x10\n\x08interval\x18\x04 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x04\x42\x03\xf8\x01\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb_hbt_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _PB_H_MSG._serialized_start=43
  _PB_H_MSG._serialized_end=138
# @@protoc_insertion_point(module_scope)
