# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trading_rule.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12trading_rule.proto\x12\x0estrategy_proto\x1a\x0c\x63ommon.proto\"\xbb\x01\n\x0cTradingLimit\x12\x1a\n\x12max_order_quantity\x18\x01 \x01(\x01\x12\x1a\n\x12max_order_notional\x18\x02 \x01(\x01\x12\x1e\n\x16max_order_notional_usd\x18\x03 \x01(\x01\x12!\n\x19max_liquidity_impact_bips\x18\x04 \x01(\x01\x12\x17\n\x0fmax_order_price\x18\x05 \x01(\x01\x12\x17\n\x0fmin_order_price\x18\x06 \x01(\x01\"\x8d\x01\n\x0bTradingRule\x12\x30\n\x07pattern\x18\x01 \x01(\x0b\x32\x1f.strategy_proto.PositionPattern\x12+\n\x05limit\x18\x02 \x01(\x0b\x32\x1c.strategy_proto.TradingLimit\x12\x0e\n\x06sticky\x18\x03 \x01(\x08\x12\x0f\n\x07\x64isable\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_rule_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRADINGLIMIT._serialized_start=53
  _TRADINGLIMIT._serialized_end=240
  _TRADINGRULE._serialized_start=243
  _TRADINGRULE._serialized_end=384
# @@protoc_insertion_point(module_scope)
